<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TekArch" name="tests.LoginTest" tests="3" failures="1" timestamp="04 Jan 2023 18:24:07 GMT" time="138.406" errors="0">
  <testcase name="loginErrorMsg_TC01" time="45.423" classname="tests.LoginTest"/>
  <testcase name="loginToSF_TC02" time="34.429" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="Free trial should be seen expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Free trial should be seen expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at tests.LoginTest.loginToSF_TC02(LoginTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- loginToSF_TC02 -->
  <testcase name="rememberMe_TC03" time="58.554" classname="tests.LoginTest"/>
</testsuite> <!-- tests.LoginTest -->
